kind: pipeline
name: default

steps:
  - name: get-private-key
    image: node:12-alpine
    environment:
      GITEA_TOKEN:
        from_secret: gitea_token
    commands:
    - npx -q gitea-secret -h git.are1000.dev -t "$GITEA_TOKEN" -r are/secrets -k ssh-keys/dokku-drone/private -o ./private_key
    - export APP_NAME='test'

  - name: test-plugin
    image: are1000/drone-ssh:19
    settings:
      private_key_path: ./private_key
      host: https://dokku.are1000.dev
      username: dokku
      env:
        APP_NAME: "{{DRONE_TAG}}-blog.iama.re"
      script:
        - apps:create "{{APP_NAME}}"
        - domains:add "{{APP_NAME}}" "{{APP_NAME}}"
        - tar:from "{{APP_NAME}}" "https://git.are1000.dev/are/blog.iama.re/releases/download/{{DRONE_TAG}}/release.tar"
        - letsencrypt "{{APP_NAME}}"