kind: pipeline
name: default

steps:
  - name: get-private-key
    image: node:10.16.0-alpine
    environment:
      GITEA_TOKEN:
        from_secret: gitea_token
    commands:
    - npx -q gitea-secret -h git.are1000.dev -t "$GITEA_TOKEN" -r are/secrets -k ssh-keys/dokku-drone/private -o ./private_key

  - name: test-plugin
    image: are1000/drone-ssh:3
    settings:
      private_key_path: ./private_key
      host: https://dokku.are1000.dev
      script:
        - dokku apps:create "{APP_NAME}"
        - dokku domains:add "{APP_NAME}" "{APP_NAME}"
        - dokku tar:from "{APP_NAME}" "https://git.are1000.dev/are/blog.iama.re/releases/download/{DRONE_TAG}/release.tar"
        - dokku letsencrypt "{APP_NAME}"